require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
